# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

#jinja:
#  # This tells HA to load your macros
#  custom_templates: !include_dir_merge_list jinja_macros

#template: !include templates.yaml

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    homeassistant.config_entries: debug
    custom_components.dpk_ek_scraper: debug

template:
  - sensor:
      - name: "Cheapest Flight Overall"
        unit_of_measurement: "GBP"
        device_class: monetary
        state: >
          {% from 'flight_macros.jinja' import select_flight %}
          {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim %}
          {% if chosen and (chosen in states) %}
            {{ states(chosen) }}
          {% else %}
            None
          {% endif %}
        attributes:
          entity: >
            {% from 'flight_macros.jinja' import select_flight %}
            {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim %}
            {{ chosen if chosen and (chosen in states) else None }}
          duration: >
            {% from 'flight_macros.jinja' import select_flight %}
            {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim %}
            {% if chosen and (chosen in states) %}
              {{ state_attr(chosen, 'duration') }}
            {% else %}
              None
            {% endif %}