# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

#jinja:
#  # This tells HA to load your macros
#  custom_templates: !include_dir_merge_list jinja_macros

#template: !include templates.yaml

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    homeassistant.config_entries: debug
    custom_components.dpk_ek_scraper: debug

template:
  - sensor:
      - name: "Cheapest Flight Overall"
        unit_of_measurement: "GBP"
        device_class: monetary
        state: >
          {% from 'flight_macros.jinja' import select_flight %}
          {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim %}
          {{ states(chosen) if chosen else 'unknown' }}
        attributes:
          entity: >
            {% from 'flight_macros.jinja' import select_flight %}
            {{ select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim }}
          duration: >
            {% from 'flight_macros.jinja' import select_flight %}
            {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest')| trim %}
            {{ state_attr(chosen, 'duration') if chosen else 'unknown' }}
      - name: "Cheapest Fastest Flight Overall"
        unit_of_measurement: "GBP"
        device_class: monetary
        state: >
          {% from 'flight_macros.jinja' import select_flight %}
          {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest_fastest')| trim %}
          {{ states(chosen) if chosen else 'unknown' }}
        attributes:
          entity: >
            {% from 'flight_macros.jinja' import select_flight %}
            {{ select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest_fastest')| trim }}
          duration: >
            {% from 'flight_macros.jinja' import select_flight %}
            {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'cheapest_fastest')| trim %}
            {{ state_attr(chosen, 'duration') if chosen else 'unknown' }}
      - name: "Fastest Flight Overall"
        unit_of_measurement: "GBP"
        device_class: monetary
        state: >
          {% from 'flight_macros.jinja' import select_flight %}
          {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'fastest')| trim %}
          {{ states(chosen) if chosen else 'unknown' }}
        attributes:
          entity: >
            {% from 'flight_macros.jinja' import select_flight %}
            {{ select_flight(states.sensor, '2026_04_11_04_22_econ', 'fastest')| trim }}
          duration: >
            {% from 'flight_macros.jinja' import select_flight %}
            {% set chosen = select_flight(states.sensor, '2026_04_11_04_22_econ', 'fastest')| trim %}
            {{ state_attr(chosen, 'duration') if chosen else 'unknown' }}
