# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

#template: !include templates.yaml

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    homeassistant.config_entries: debug
    custom_components.dpk_ek_scraper: debug
